name = "desert-derby"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

[vars]
PAYMENT_ADDRESS = "SPKH9AWG0ENZ87J1X0PBD4HETP22G8W22AFNVF8K"

[[kv_namespaces]]
binding = "GAMES"
id = "bc4f46980a494061814117787076a5f0"
